const INITIAL_INVESTMENT_AMOUNT_USD = 10000;
const SESSION_TIMEOUT_MILLI = 600000; // 10 minutes in milliseconds
const EXCHANGE_UPDATE_INTERVAL_MILLI = 900000; // 15 minutes
const HISTORY_DAYS = 7; // number of days to keep historical data
const ONE_DAY_MILLI = 24 * 60 * 60 * 1000; // one day in milliseconds
const HISTORICAL_RATES_UPDATE_INTERVAL_MILLI = 12 * 60 * 60 * 1000; // 12 hours
module.exports = {
  INITIAL_INVESTMENT_AMOUNT_USD,
  SESSION_TIMEOUT_MILLI,
  EXCHANGE_UPDATE_INTERVAL_MILLI,
  HISTORY_DAYS,
  ONE_DAY_MILLI,
  HISTORICAL_RATES_UPDATE_INTERVAL_MILLI,
};
